"""
Django settings for vallgal project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-gg!wswc+ku)2janmvovnvh!$4ux37cn4ky--3w3)i2br+62go2'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

SESSION_COOKIE_AGE = 604800
# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',


    # modified user model, etc.
    'profiles',
    

    # just regular pages
    'pages',

    # mikes awesome support tickets
    'support',

    # news app
    'news',

    # store app
    'store',

    # staff admin panel
    'staff',

    # teams
    'teams',

    # matches for all uses
    'matches',

    # single elimination tournaments
    'singletournaments',

    # wagers
    'wagers',

    'leagues',

    # ip package
    'ipware',

    # paypal IPN
    'paypal.standard.ipn',

    # the country field
    'django_countries',

    # object storage
    'storages',

    # rich text fields
    'ckeditor',

    # this is what handles deleting old uploaded files
    # NmOTE: THIS MUST BE LAST IN THE LIST
    'django_cleanup.apps.CleanupConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'vallgal.middleware.ban_middleware',
]

ROOT_URLCONF = 'vallgal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'vallgal.context_processors.site_info'
            ],
        },
    },
]

WSGI_APPLICATION = 'vallgal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATIC_ROOT = '/static/'
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "project-static")
]

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, '/media/')

# Where to redirect users after login
LOGIN_REDIRECT_URL = '/'
LOGIN_URL = '/login/'

GOOGLE_RECAPTCHA_SECRET_KEY = '6LdMtHIfAAAAAHf9Yvv1pWucMG-hekVXHxA1cJXb'
GOOGLE_RECAPTCHA_SITE_KEY = '6LdMtHIfAAAAAFCl7KjWdCQyx66BtPCVsQFLUyJK'

ESPORTS_MODE = True
USER_VERIFICATION = False
PAYPAL_TEST = False
STORE_ENABLED = True
WAGERS_ENABLED = False

# Email stuff
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'desis1tinfo@gmail.com'
EMAIL_HOST_PASSWORD = '311694MKs'

try:
    FROM_EMAIL = "desis1tinfo@gmail.com"
except IndexError:
    FROM_EMAIL = "desis1tinfo@gmail.com"
except KeyError:
    FROM_EMAIL = "MySite <noreply@example.com>"

EMAIL_PORT = 587

SITE_NAME = 'CSC'
SITE_SERVER = 'CSC'
SITE_VERSION = "1.0.4"